name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - run: npm install
      - run: npm run build
      
      - name: deploy
        run: |
          cd ./dist/QuizNG-frontend
          git init
          git config --global user.email "${{secrets.EMAIL}}"
          git config --global user.name "${{secrets.USERNAME}}"
          git config --global init.defaultBranch master
          git remote add origin https://github.com/${{github.actor}}/weebNeedWeed.github.io.git
          git branch -m master
          git add .
          git commit -m "Hello"
          git push -f origin master
